# Generated by Django 5.2.4 on 2025-07-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_lat', models.FloatField()),
                ('shop_lng', models.FloatField()),
                ('customer_lat', models.FloatField()),
                ('customer_lng', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('picked', 'Picked from Shop'), ('delivering', 'Out for Delivery'), ('delivered', 'Delivered to Customer')], default='pending', max_length=15)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
